name: lexa_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.4
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.4.3
  provider: ^6.1.2
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.18
  flutter_svg: ^1.1.6
  cupertino_icons: ^1.0.5
  animated_splash_screen: ^1.3.0
  google_generative_ai: ^0.4.4
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/cratoss_logo.png
